apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: videoproxy
  name: videoproxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: videoproxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: videoproxy
    spec:
      containers:
        - env:
            - name: YOUTUBE_API_KEY
              value: yourkey
          image: suconghou/videoproxy
          imagePullPolicy: Always
          name: videoproxy
          ports:
            - containerPort: 6060
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: videoproxy
  annotations:
    dev.okteto.com/auto-ingress: 'true'
spec:
  ports:
    - port: 6060
      protocol: TCP
      targetPort: 6060
  selector:
    run: videoproxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
