apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ws
  name: ws
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: ws
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: ws
    spec:
      containers:
        - image: suconghou/signalserver
          imagePullPolicy: Always
          name: ws
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ws
  annotations:
    dev.okteto.com/auto-ingress: 'true'
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    run: ws
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
